### ISSUE TITLE
Отправка почты

### ISSUE THREAD

**Issue by alexey1607** [jfhs/simple-gallery#1]
Привет,
sys call надо подправить  в index.php
` system('echo "Photo" | mail -a '.escapeshellarg(realpath(SCANDIR)."/".$path).' -v -s '.escapeshellarg("Photo from me!").' '.escapeshellarg($_POST['email']));`

Настройка почты
```
yum install mailx
vi /etc/mail.rc
set smtp=smtps://smtp.gmail.com:465
set smtp-auth=login
set smtp-auth-user=mail@gmail.com
set smtp-auth-password=password
set ssl-verify=ignore
set nss-config-dir=/etc/pki/nssdb/
```

**Comment by jfhs** [comment]
Спасибо, обновил
